/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as ProgramasRouteImport } from './routes/programas'
import { Route as MunicipiosRouteImport } from './routes/municipios'
import { Route as MulheresRouteImport } from './routes/mulheres'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CasosRouteImport } from './routes/casos'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AtendimentosRouteImport } from './routes/atendimentos'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as IndexRouteImport } from './routes/index'

const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramasRoute = ProgramasRouteImport.update({
  id: '/programas',
  path: '/programas',
  getParentRoute: () => rootRouteImport,
} as any)
const MunicipiosRoute = MunicipiosRouteImport.update({
  id: '/municipios',
  path: '/municipios',
  getParentRoute: () => rootRouteImport,
} as any)
const MulheresRoute = MulheresRouteImport.update({
  id: '/mulheres',
  path: '/mulheres',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CasosRoute = CasosRouteImport.update({
  id: '/casos',
  path: '/casos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentosRoute = AtendimentosRouteImport.update({
  id: '/atendimentos',
  path: '/atendimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/atendimentos': typeof AtendimentosRoute
  '/auth': typeof AuthRoute
  '/casos': typeof CasosRoute
  '/dashboard': typeof DashboardRoute
  '/mulheres': typeof MulheresRoute
  '/municipios': typeof MunicipiosRoute
  '/programas': typeof ProgramasRoute
  '/relatorios': typeof RelatoriosRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/atendimentos': typeof AtendimentosRoute
  '/auth': typeof AuthRoute
  '/casos': typeof CasosRoute
  '/dashboard': typeof DashboardRoute
  '/mulheres': typeof MulheresRoute
  '/municipios': typeof MunicipiosRoute
  '/programas': typeof ProgramasRoute
  '/relatorios': typeof RelatoriosRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/atendimentos': typeof AtendimentosRoute
  '/auth': typeof AuthRoute
  '/casos': typeof CasosRoute
  '/dashboard': typeof DashboardRoute
  '/mulheres': typeof MulheresRoute
  '/municipios': typeof MunicipiosRoute
  '/programas': typeof ProgramasRoute
  '/relatorios': typeof RelatoriosRoute
  '/usuarios': typeof UsuariosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alertas'
    | '/atendimentos'
    | '/auth'
    | '/casos'
    | '/dashboard'
    | '/mulheres'
    | '/municipios'
    | '/programas'
    | '/relatorios'
    | '/usuarios'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alertas'
    | '/atendimentos'
    | '/auth'
    | '/casos'
    | '/dashboard'
    | '/mulheres'
    | '/municipios'
    | '/programas'
    | '/relatorios'
    | '/usuarios'
  id:
    | '__root__'
    | '/'
    | '/alertas'
    | '/atendimentos'
    | '/auth'
    | '/casos'
    | '/dashboard'
    | '/mulheres'
    | '/municipios'
    | '/programas'
    | '/relatorios'
    | '/usuarios'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertasRoute: typeof AlertasRoute
  AtendimentosRoute: typeof AtendimentosRoute
  AuthRoute: typeof AuthRoute
  CasosRoute: typeof CasosRoute
  DashboardRoute: typeof DashboardRoute
  MulheresRoute: typeof MulheresRoute
  MunicipiosRoute: typeof MunicipiosRoute
  ProgramasRoute: typeof ProgramasRoute
  RelatoriosRoute: typeof RelatoriosRoute
  UsuariosRoute: typeof UsuariosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programas': {
      id: '/programas'
      path: '/programas'
      fullPath: '/programas'
      preLoaderRoute: typeof ProgramasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/municipios': {
      id: '/municipios'
      path: '/municipios'
      fullPath: '/municipios'
      preLoaderRoute: typeof MunicipiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mulheres': {
      id: '/mulheres'
      path: '/mulheres'
      fullPath: '/mulheres'
      preLoaderRoute: typeof MulheresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/casos': {
      id: '/casos'
      path: '/casos'
      fullPath: '/casos'
      preLoaderRoute: typeof CasosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimentos': {
      id: '/atendimentos'
      path: '/atendimentos'
      fullPath: '/atendimentos'
      preLoaderRoute: typeof AtendimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertasRoute: AlertasRoute,
  AtendimentosRoute: AtendimentosRoute,
  AuthRoute: AuthRoute,
  CasosRoute: CasosRoute,
  DashboardRoute: DashboardRoute,
  MulheresRoute: MulheresRoute,
  MunicipiosRoute: MunicipiosRoute,
  ProgramasRoute: ProgramasRoute,
  RelatoriosRoute: RelatoriosRoute,
  UsuariosRoute: UsuariosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
